### ISSUE TITLE
[BUG] mappers with matching types not found in Add new connector dialog

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#347]
to reproduce:
1) create an interface with two classes and create a connector - ex
  - BBM_SalesforceStreamBase
  - BBM_CreateOrder
2) create a mapper for the connector and save everything
3) delete the connector and recreate it and then try to choose a mapper

the existing mapper with compatible types is not shown - instead you get:
<img width="1720" alt="Screen Shot 2020-02-12 at 8 15 55 AM" src="https://user-images.githubusercontent.com/13432105/74311495-ebbd9400-4d6f-11ea-9f4c-74ce385936d6.png">

**Comment by Foxhoundn** [comment]
This works fine for me, @turlyalz can you please test it? I have no issues here.

**Comment by davidnich** [comment]
@Foxhoundn I just tested it with v 1.0.1 (build from < 1 hour ago), and it's still happening.

The scenario above is the one I am still testing, and it still doesn't work. 

Here is a screenshot of the IDE from this scenario - the connector was made, the mapper created, and then the connector is reopened and clicking on the edit mapper button on the connector shows the following:
<img width="1574" alt="Screen Shot 2020-02-21 at 6 20 53 PM" src="https://user-images.githubusercontent.com/13432105/75056477-648ebf80-54d7-11ea-8e18-157eaf06acb3.png">

In this case the IDE should show the same mapper that was already created for the connector at least.

**Comment by davidnich** [comment]
the `get-mappers` frontend msg is being sent, but the `return-mappers` backend response is never received:
<img width="1050" alt="Screen Shot 2020-02-21 at 11 38 30 PM" src="https://user-images.githubusercontent.com/13432105/75078612-5c01ad80-5506-11ea-9ff7-1864096104b1.png">

**Comment by Foxhoundn** [comment]
Fixed.

**Comment by davidnich** [comment]
this is now almost working.  The mappers are now shown in the dialog box if they already exist.

The use case that's not working is the one I need for the demo - which is working in the 12.2 version of the IDE.

That use case if the one documented above - when you create the mapper for the first time in the connection dialog when you go back to the dialog, I still get the screen above in the second screenshot - where it says there is no mapper, but allows you to edit it.

Later, when you save it and go back, the dialog box looks correct, and the mapper is visible.

**Comment by davidnich** [comment]
after updating the out-of-date mappers, the problem goes away, however all mappers are shown in the connector box, and not just the compatible ones, so that needs to be fixed, as well as ignoring completely invalid mappers.

**Comment by davidnich** [comment]
only compatible mappers are shown now - looks fixed
